### ISSUE TITLE
increment_address_value_in_child_process function 

### ISSUE THREAD

**Issue by ali-zohrevand** [hiikezoe/android_run_root_shell#22]
hi a gain ...
sorry for asking a lot :(
in line 127 function increment_address_value_in_child_process
why the offset is  (int)(address - perf_swevent_enabled) / 4
address is ptmx_fsync_address = ptmx_fops_address + 0x38 right??
then what is Relation of address with perf_swevent_enabled address??
there is no good reference in the net for it ...

**Comment by hiikezoe** [comment]
Actually I don't remember exactly what the codes mean, but the answer sits in the kernel source code. Please read the kernel source code for your device.
